apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.name }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Chart.Name }}
    component: backend
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://{{ .Values.database.host }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.database.port }}/{{ .Values.database.name }}?{{ .Values.database.jdbcParams }}"
  DB_USERNAME: {{ .Values.database.username | quote }}
  DB_PASSWORD: {{ .Values.database.password | quote }}
